name: Deploy Database

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build and deploy Postgres container
      run: |
        docker-compose --env-file .env up -d

    - name: Test connection to PostgreSQL
      run: |
        docker exec -it ${CONTAINER_NAME_DATABASE} pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
